"""novos camos para o player

Revision ID: 3cde3f4eb0af
Revises: 8ae422aa9e6f
Create Date: 2023-08-22 22:58:31.870276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cde3f4eb0af'
down_revision = '8ae422aa9e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('damage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('speed')
        batch_op.drop_column('damage')
        batch_op.drop_column('life')

    # ### end Alembic commands ###
