WIDTH, HEIGHT = 854, 480
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
RESOLUTION = (WIDTH, HEIGHT)
SCALE = 3
FPS = 60

PLAYER_IMAGE_PATH = "assets/sprites/warrior/sprite.png"

# Animations ID
PLAYER_IDLE = 1
PLAYER_RUN = 2

# Tilesets
FLOOR_TILES = [1, 2]
WALL_TILES = [3]